# Generated by Django 5.1 on 2024-09-15 08:17

import django.db.models.deletion
import mesa.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('produto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('status', models.CharField(default='Fechada', max_length=10)),
                ('pedido', models.PositiveIntegerField(default=0)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pessoas_pagaram', models.IntegerField(default=0)),
                ('numero_pessoas', models.IntegerField(default=1)),
                ('empresa', models.ForeignKey(default=mesa.models.get_empresa_padrao, on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='empresa.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='mesa.mesa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='produtos',
            field=models.ManyToManyField(through='mesa.Pedido', to='produto.produto'),
        ),
    ]
